include: "https://gitlab-templates.ddbuild.io/slack-notifier/sdm/template.yml"

stages:
  - test
  - after-test
  - check-downstream
  - notify

.skip_stable_branches: &skip_stable_branches
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^7.[0-9]{2}.x/
      when: never
    - if: $CI_COMMIT_TAG != null
      when: never
    - when: always

trigger-agent-build:
  <<: *skip_stable_branches
  stage: test
  trigger:
    project: datadog/datadog-agent
    strategy: depend
  variables:
    OMNIBUS_SOFTWARE_VERSION: $CI_COMMIT_BRANCH
    RUN_ALL_BUILDS: "true"
    RUN_KITCHEN_TESTS: "true"

on_success:
  <<: *skip_stable_branches
  stage: after-test
  needs: ["trigger-agent-build"]
  tags: ["arch:amd64"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:v19805261-b468a29
  when: on_success
  script:
    - echo success > output.pipeline
  artifacts:
    paths:
      - output.pipeline
    expire_in: 1 week

check-downstream-pipeline:
  <<: *skip_stable_branches
  stage: check-downstream
  tags: ["arch:amd64"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:v19805261-b468a29
  when: always
  script:
    - cat output.pipeline

notify:
  extends: .slack-notifier-base
  stage: notify
  dependencies: []
  <<: *skip_stable_branches
  script: |
    export MESSAGE="Your omnibus-software test pipeline completed"
    /usr/local/bin/notify.sh

