include: "https://gitlab-templates.ddbuild.io/slack-notifier/v3-sdm/template.yml"

stages:
  - notify

notify:
  extends: .slack-notifier-base
  stage: notify
  dependencies: []
  rules:
    - when: always
  script: |
    export MESSAGE="Your omnibus-software test pipeline completed"
    /usr/local/bin/notify.sh
