stages:
  - generation
  - trigger

check_if_branch_is_a_pr:
  stage: generation
  tags: ["arch:amd64"]
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/deb_x64:v48815877-9bfad02c
  allow_failure: true
  script: |
    cp .generated-pipeline.yml generated-pipeline.yml
    # Check if our current branch is inside the PR list of omnibus-software
    echo "$CI_COMMIT_REF_NAME"
    if curl https://api.github.com/repos/DataDog/omnibus-software/pulls | grep "$CI_COMMIT_REF_NAME"
    then
      echo "Current commit is on a PR"
      cp .gitlab-ci-agent-build.yml generated-pipeline.yml
    else
      echo "Current commit is not on a PR"
    fi
  artifacts:
    untracked: true
    expire_in: 1h
    paths:
      - generated-pipeline.yml

trigger_pipeline:
  stage: trigger
  needs:
    - job: check_if_branch_is_a_pr
      artifacts: true
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: check_if_branch_is_a_pr


