stages:
  - generation
  - trigger

check_if_branch_is_a_pr:
  stage: generation
  tags: ["arch:amd64"]
  image: registry.ddbuild.io/ci/datadog-agent-buildimages/deb_x64:v48815877-9bfad02c
  allow_failure: true
  script: |
    if curl https://api.github.com/repos/DataDog/omnibus-software/pulls | grep "$CI_COMMIT_REF_NAME"
    then
      cp .gitlab-ci-agent-build.yml generated-pipeline.yml
    fi

trigger_pipeline:
  stage: trigger
  needs:
    - check_if_branch_is_a_pr
  trigger:
    include:
      - local: ./generated-pipeline


