version: 2.1

jobs:
  hello:
    docker:
      - image: ruby:2.3.1
    steps:
      - checkout
      - run: gem install bundler -v 1.17.3 --no-document
      - run: bundle install --jobs 7
      - run: bundle exec rake


workflows:
  say_hello:
    jobs:
      - hello