name: Open datadog-agent PR
run-name:
on:
  pull_request:
    #    types:
    #      - closed

jobs:
  open_pr:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Empty dummy workflow
        run: echo "nothing to do yet"
#       - name: Clone datadog-agent repo
#         uses: actions/checkout@v3
#         with:
#           repository: github.com/datadog/datadog-agent
#
#       - name: Update release.json
#         run: cd datadog-agent && inv -e release.set_release_json ${GITHUB_SHA}
#
#       - name: create datadog-agent PR
#         uses: peter-evans/create-pull-request@v5
#         with:
#           base: main
#           delete-branch: true
#           path: datadog-agent
#           add-paths: release.json
#           commit-message: 'omnibus: bump OMNIBUS_SOFTWARE_VERSION'
#           title: '[omnibus][automated] Bump OMNIBUS_SOFTWARE_VERSION'
#           branch: 'automated/omnibus-software/${{ github.event.number }}'
