name: Disable auto bump PR
on:
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
